[project]
name = "finance-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mypy>=1.15.0",
    "numpy>=2.2.3",
    "polars>=1.22.0",
    "ruff>=0.9.7",
    "streamlit>=1.42.2",
    "yfinance>=0.2.54",
]
